language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g --silent @angular/cli
script: 
- ng build --prod
deploy:
  provider: cloudfoundry
  skip_cleanup: true
  username: 
     secure: "pBk1qZKrxFONQLv15pkmhY10vuMD3qhbOqnwDzR8spRm8O1LhWG0cf6/NzK46vxiPSHVcIzaoWx444jr5pLdpcjlH0DTEUvbM+CywsduKhiwmFmb18LlwNkWFdA6nN5pF/Ukhd4DJpA5rbLP4tKC3z/1tpk+p0Uhj3HPmwhTrORyKPCws78frfH1CqNXavfkVywvLV0E/TljzpmQanCAWkbY6XGKTctBbEifUMbxfTLtqS1t96yks+RH4iBmOOMlgUTcdKsR1vTFJw4HmrN5MBd43+f5+FDPQh/rj1NEaAK1ifopFKuHO1dF2UWCXkr+NzwVE5ylpzvmaZDF4N10WMkqqYWX3aD+u868ZFM3vyCkhmRvwUDuivqpXOuI3mwmZRAtWhvxVp1LKsLD/gORUJyQl2tptcLUSbFqGg1iR3zPNh+gDizgP+ErnxJMdTqh4BSQ9XMGViT7zBHtRWZjlpFGojcODDqZJ5SgyMDaQB2BBg2TcxZ9v6VUex6DWtkQMWgWcqYziRXdTnrB+GJ9/koo59mwlPmQQfVXy2KwXBIEE6IRNW6+7e82+KFagQZyImHYjVwgsxt3/xl3zP84ZQWKdWQ0miYVHlwCvmScQywQCAtZKCxYjmyAMIDmzUhx4QpKFJiXgAiyOF1SiTsYZW+KQG9GMzoYNHRqdLzBfzA="
  password: 
     secure: "OYUEoZKgDsfQGygB9oJS9YkKx659ixjOzUtN4o6wpYyAP115AldpMeuOt6iJaQd37Uw8f6J7tl9aCLTJE5AOo8RnTpZsIM3/Mrx6XydYZDM2Umn6Dbpp8NeEkIVnROrWDco8dy7hrS72Rz5ewho10hSCkyZ5lVIHV7k78jFC2nkCdIYGpFnpmKSUGNYdwyA/EL6RWJPuyaZEvX/ojRz9pwJIw3jUo5DJgy0LRbWKNOf/2o0jY5ubOep4upaFA7clO7NSDD0+G0A8v2wZpHG0+lWsNcODhtmAuoUy2Ao8JKoHfk5Va531XzfFgnZdkGZHRzA2scI6vaWEc3DpuYt3CRgP4R3Kjz51htxvJ2RUh9WU2VfPVIdOoUn41RpGbCL7f3OYF8T5Z+481HslLhDIzWaYhcuUAv3QIGw4gWS715mo3PxgeH7OMkmBSuAeCfcx1iLTaAwpwbYpBSNFH6s/BwQ2dp890xVGBDLtb0ZolBmgSZZwug7htOaTr4MM/poNWpMLvGOVJ2ax8LtK6KGdh1SJI9UP9Z/HKrdaOjdmzNBvCotvTCmM/Rpd7m+Cp5tIic/xEVgzf1+8KdYzQgslSYlj622t3twrNTCBnXhTJ6Dc1XSu70Q77PcAHcGDwSCvBRJUGMgkmJX4h0vRPjS/U0yLlf/g/Mgje016VKlK8hk="
  api: https://api.run.pivotal.io
  organization: 
     secure: "TJV/7HJlrDj8kmTFAi+yq/9gdFVK50CWwJ0ugjjdyT5dpwreO2lGXIvqZAfhl5kEwEiFolJnRdxhDfVx/pnXwnaGLTdl6EOeeAEZA2YpJZEDilJVpujRqD+bJa12zYuHYRlubFTqsctBeEQGOkbzt7m+7JAru8ZBA2UP65xwv2o7DhFiSOnRpuU90q8TnGGmbO2VYWqyz+zfzTmpcygbqZFcmwJPkQ3wd76ixzGTo/M57Ko+NMWIUhdjgOnGQbXwjXrppjV0aGjgjXp01eTWgXuD8Ww5lE4S1MoN2tvIcarotF/F4nvvBIT4kpGXd+uIWTAQlkL2kGT0w0n4wjLNK7kjzRuJBGlq7VAHb9Eom/562YDhqgVk2MFE+RFQm6kXRbHmrSxNyfB0srd3o6cQVlGUKHK+eq6+QfDkABR8WHAJCv5YYe//x5Lel6Btef+JS1sHEn2DJwvDXtnB0l9zd230dOcXUTg0MrREra4vP0zBpWq3RXSlmQHYJM5IXztlZJ8ExxNjlxRDD1Uqqp0jTM0IHQ3voLujUFpOQMNdXfqAXJhrxjgDoKnx37Hb1uMA2bBr7tfI0bxgbBCUXRUxh7ad8zQJPKv5szqj9LXQcJPm/gP44SUo/A4whCDg3qxf0MKYq3XNaScx4NlYgubAuLYIJI/n3RUOf/DtuInrmp4="
    
  space: development
notifications:
  email:
    on_failure: change
    on_success: change
